import type { Metadata } from "next"
import { Work_Sans as WorkSans } from "next/font/google"
import NavBar from "src/components/nav-bar"
import "ui/styles/globals.css"
import "./globals.css"
import { Toaster } from "@shadui/sonner"

const fontBase = WorkSans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "therealryanphan",
  description: "Generated by create turbo with love"
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={fontBase.className}>
        <Toaster richColors position="top-right" />
        <NavBar className="border-gray-30 border-b" />
        <main className="mx-auto w-full max-w-5xl sm:p-4">{children}</main>
      </body>
    </html>
  )
}
