import Header from "@/components/header"
import "@/styles/globals.css"
import { Toaster } from "@shadui/sonner"
import { cn } from "@shared-utils/cn"
import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"
import React from "react"

const fontBase = GeistSans

export const metadata: Metadata = {
  title: "therealRYANPHAN",
  description: "Generated by create turbo with love"
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>): React.ReactElement {
  return (
    <html lang="en">
      <body className={cn(fontBase.className, "mx-4 flex max-w-2xl flex-col antialiased lg:mx-auto")}>
        <Toaster position="top-right" richColors />
        <Header />
        <main className="mx-auto w-full max-w-5xl px-8 pb-10 pt-8 sm:p-4 sm:pb-20">{children}</main>
      </body>
    </html>
  )
}
